### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ShixiangWang** [hiplot/hiplot-plugin-generator#1]
Link to https://github.com/hiplot/gold/issues/158

Shiny

- [x] 完成原计划开发内容：包括函数名键入、函数参数编辑、生成 hiplot plugin 4 个所需文件，另外支持导入自定义函数脚本
- [ ] 优化：开发 ggpubr barplot 实际测试目前 shiny 的使用效果，解决可能存在的问题

会存在的问题：

- 需要开发者了解相关 json 的编辑并正确设置
- 难以调试

更高级，脱离 Shiny：

- [x] 设计接口和工具实现注释到 Hiplot plugin 插件转换
- [x] 测试和优化
- [ ] 类似 CRAN 提供一个统一的插件开发指南学习、提交、发布服务？

**Comment by ShixiangWang** [comment]
https://github.com/hiplot/hiplot-plugin-generator/blob/master/test_parser.R 大家可以查看和完善下

**Comment by ShixiangWang** [comment]
Todo List:

- [x] 支持 dataArg
- [x] 支持基础绘图函数
- [x] 支持文件目录结果
- [x] 支持文件输入
- [ ] 需要一个实时预览插件（general 参数需要自动补充上去）
- [x] 协调处理好一些细节问题
- [ ] 开发文档构建，特别是支持的 vue 控件类型（lib.R 中支持的函数应当加入文档，以及 conf, opt）
- [x] 补充 `hisub.R` 中的控件支持 （只要 hiplot 本身支持，就可以通过 json 设定）

**Comment by ShixiangWang** [comment]
https://hiplot.com.cn/basic/pcatools 作为示例

**Comment by ShixiangWang** [comment]
https://hiplot.com.cn/docs/zh/development-guides/ 目前的开发指南

**Comment by ShixiangWang** [comment]
使用方法用户提交一个 README.md 文件，我直接拷贝到插件目录即可。

中英文分开？

**Comment by ShixiangWang** [comment]
对了 还有一个小细节，data 字段最好在解析之后前面加上 1-datTable, 2-sampleInfo 这种数字编号前缀，避免有些字段值缺失之后造成错位。

**Comment by ShixiangWang** [comment]
后续主要增加 3 方面的文档：

- [ ] 通用参数（一般是为 ggplot2 设定的）
- [ ] vue 控件类型和常用参数
- [ ] conf 和 opt 这两个全局变量

hiplot-textarea, combobox, autocomplete, text-field, slider, range-slider, switch, and color-picker

**Comment by ShixiangWang** [comment]
@Miachol 剑峰，有空能否下线 https://hiplot.com.cn/developer/plugin-generator，然后支持一个预览插件，类似 https://hiplot.com.cn/developer/plugin-preview，但只需要输入 R 脚本内容，点击后后台运行插件生成工具？
